{% set version = "0.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-isingfit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/IsingFit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/IsingFit/IsingFit_{{ version }}.tar.gz
  sha256: 18ab6a8d366fc8d1c4ff8305419b97b28503820ffd84dbc2d3ec1012e550b7df

build:
  number: 1
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-matrix
    - r-glmnet
    - r-qgraph

  run:
    - r-base
    - r-matrix
    - r-glmnet
    - r-qgraph

test:
  commands:
    - $R -e "library('IsingFit')"           # [not win]
    - "\"%R%\" -e \"library('IsingFit')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=IsingFit
  license: GPL-2.0-only
  summary: This network estimation procedure eLasso, which is based on the Ising model, combines l1-regularized logistic regression with model selection based on the Extended Bayesian Information Criterion (EBIC). EBIC is a fit measure that identifies relevant relationships between variables. The resulting network consists
    of variables as nodes and relevant relationships as edges. Can deal with binary data.

  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
